stages:
- test

variables:
  CONTAINER_IMAGE: registry.gitlab.com/kyashar/dashboard
  CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME
  DEPLOY_SERVER_URL: onniquedesmeres.fr
#  DEPLOY_PATH: /var/data/myapp

test:
  stage: test
  tags:
  - shell
  script:
  - docker-compose -f docker-compose.test.yml -p ci up --abort-on-container-exit
  coverage: '/TOTAL.*?(\d{1,2}.\d+%)/'
  after_script:
  - make delete

