image: registry.gitlab.com/kyashar/cpp_rtype

stages:
    - compilation

compilation:
  stage: compilation
  script:
          #    - git submodule update --init --recursive
    - export DISPLAY=:0.0
    - mkdir build
    - cd build
    - cmake ..
    - make -j 3
    - ./bin/ServerTest
    - ctest
  after_script:
    - cat ./build/log.txt
