image: debian:stretch

compilation:
  script:
    - apt-get update
    - apt-get install -y git cmake g++ gcovr
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake ..
    - make

test:
  script:
    - cd build
    - ctest
