image: debian:stretch

stages:
    - compilation
    - test

compilation:
  stage: compilation
  tages:
    - shell
  script:
    - apt-get update
    - apt-get install -y git cmake g++ gcovr
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake ..
    - make

test:
  stage: test
  tages:
    - shell
  script:
    - cd build
    - ctest
